language: cpp
sudo: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - swig
          - python-dev
          - python-numpy
          - guile-2.0-dev
          - liboctave-dev
          - cmake
          - g++-mingw-w64-i686
          - gcc-mingw-w64-i686
          - binutils-mingw-w64-i686
          - g++-mingw-w64-x86-64
          - gcc-mingw-w64-x86-64
          - binutils-mingw-w64-x86-64
      script:
        - pip install mkdocs python-markdown-math --user
        - PATH=$PATH:~/.local/bin mkdocs build
        - mkdir build && pushd build
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DNLOPT_CXX=ON -DNLOPT_GUILE=OFF -DNLOPT_MATLAB=OFF ..
        - make install -j2 && ctest -j2 --output-on-failure
        - rm -rf * ~/.local
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_GUILE=OFF -DNLOPT_MATLAB=OFF -DCMAKE_TOOLCHAIN_FILE=$PWD/../cmake/toolchain-i686-w64-mingw32.cmake ..
        - make install -j2
        - rm -rf * ~/.local
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DNLOPT_CXX=ON -DNLOPT_PYTHON=OFF -DNLOPT_OCTAVE=OFF -DNLOPT_GUILE=OFF -DNLOPT_MATLAB=OFF -DCMAKE_TOOLCHAIN_FILE=$PWD/../cmake/toolchain-x86_64-w64-mingw32.cmake ..
        - make install -j2

    - os: osx
      install:
        - brew update
        # TODO: install guile once 2.2 is supported in swig
        - brew install swig octave || echo "nope"
      script:
        - mkdir build && pushd build
        - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DNLOPT_CXX=ON -DPYTHON_EXECUTABLE=/usr/bin/python ..
        - make install && ctest --output-on-failure
